update action.yml
Signed-off-by: GuillaumeFalourd <guillaume.falourd@zup.com.br>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,8 +23,8 @@ inputs:
 
 outputs:
   diff-output:
-    description: "Diff output"
-    value: ${{ steps.diff.outputs.result }}
+    description: "Comparision output"
+    value: ${{ steps.comparision.outputs.result }}
 
 runs:
   using: "composite"
@@ -42,50 +42,50 @@ runs:
         echo 🚀 Command OUTPUT exported to output.txt file
       shell: bash
 
-    - name: Diff commands
-      id: diff
+    - name: Comparision
+      id: comparision
       run: |
-        if [ ! -z "${{ inputs.contains }}" ]; then
-          echo 🕵️ Check if output file contains expression \"${{ inputs.contains }}\"
-          if grep -q "${{ inputs.contains }}" output.txt; then
-            result=$(echo "PASSED")
-          else
-            result=$(echo "FAILED")
-          fi
-        elif [ -z ${{ inputs.specific_line }} ]; then
-          echo 🕵️ Comparing files
-          if diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) >/dev/null; then
-            result=$(echo "PASSED")
-          else
-            result=$(echo "FAILED")
-          fi
+        if [ ! -z ${{ inputs.contains }} ]; then
+            echo 🕵️ Check if output file contains expression \"${{ inputs.contains }}\"
+            if grep -q "${{ inputs.contains }}" output.txt; then
+                result=$(echo "PASSED")
+            else
+                result=$(echo "FAILED")
+            fi
+        elif [ ! -z ${{ inputs.specific_line }} ]; then
+            echo 🕵️ Comparing files specific line
+            if diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) >/dev/null; then
+                result=$(echo "PASSED")
+            else
+                result=$(echo "FAILED")
+            fi
         else
-          echo 🕵️ Comparing files specific line
-          if diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) >/dev/null; then
-            result=$(echo "PASSED")
-          else
-            result=$(echo "FAILED")
-          fi
+            echo 🕵️ Comparing files
+            if diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) >/dev/null; then
+                result=$(echo "PASSED")
+            else
+                result=$(echo "FAILED")
+            fi
         fi
         echo "::set-output name=result::$(echo $result)"
       shell: bash
 
     - run: |
-        echo 👉 DIFF OUTPUT value is ${{ steps.diff.outputs.result }}
+        echo 👉 DIFF OUTPUT value is ${{ steps.comparision.outputs.result }}
         echo 👉 DIFF EXPECTED value is ${{ inputs.expected_result }}
-        if [ ${{ steps.diff.outputs.result }} != ${{ inputs.expected_result }} ]; then
-          echo "❌ DIFF OUTPUT value NOT EQUAL to DIFF EXPECTED value!"
-          if [ ! -z "${{ inputs.contains }}" ]; then
-            echo "Command output doesn't contain \"${{ inputs.contains }}\""
-            cat output.txt
-          elif [ -z ${{ inputs.specific_line }} ]; then
-            diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) | cat -t
-          else
-            diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) | cat -t
-          fi
-          exit 1
+        if [ ${{ steps.comparision.outputs.result }} != ${{ inputs.expected_result }} ]; then
+            echo "❌ DIFF OUTPUT value NOT EQUAL to DIFF EXPECTED value!"
+            if [ ! -z ${{ inputs.contains }} ]; then
+                echo "Command output doesn't contain \"${{ inputs.contains }}\""
+                cat output.txt
+            elif [ ! -z ${{ inputs.specific_line }} ]; then
+                diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) | cat -t
+            else
+                diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) | cat -t
+            fi
+            exit 1
         else
-          echo ✅ DIFF OUTPUT value EQUAL to DIFF EXPECTED value!
+            echo ✅ DIFF OUTPUT value EQUAL to DIFF EXPECTED value!
         fi
       shell: bash
 
